/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 267e8c3c9fc4705f0aea80129ce9a6fe)
interface __BaseEnv_Env {
	MANIFEST_CACHE: KVNamespace;
	RELEASES_BUCKET: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "staging" | "prod" | "dev";
	APP_ID: "trace";
	GITHUB_OWNER: "Eitan-S-23";
	GITHUB_REPO: "Trace";
	MANIFEST_CACHE_TTL_SECONDS: "60";
	DOWNLOAD_TOKEN_TTL_SECONDS: "300";
	DOWNLOAD_TOKEN_KEY_VERSION: "staging" | "prod" | "dev";
	RATE_LIMIT_WINDOW_SECONDS: "60";
	RATE_LIMIT_MAX_REQUESTS: "60";
	ENABLE_DIRECT_ADMIN_API: "false";
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RateLimiter";
	}
	interface StagingEnv {
		MANIFEST_CACHE: KVNamespace;
		RELEASES_BUCKET: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "staging";
		APP_ID: "trace";
		GITHUB_OWNER: "Eitan-S-23";
		GITHUB_REPO: "Trace";
		MANIFEST_CACHE_TTL_SECONDS: "60";
		DOWNLOAD_TOKEN_TTL_SECONDS: "300";
		DOWNLOAD_TOKEN_KEY_VERSION: "staging";
		RATE_LIMIT_WINDOW_SECONDS: "60";
		RATE_LIMIT_MAX_REQUESTS: "60";
		ENABLE_DIRECT_ADMIN_API: "false";
		RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
	}
	interface ProdEnv {
		MANIFEST_CACHE: KVNamespace;
		RELEASES_BUCKET: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "prod";
		APP_ID: "trace";
		GITHUB_OWNER: "Eitan-S-23";
		GITHUB_REPO: "Trace";
		MANIFEST_CACHE_TTL_SECONDS: "60";
		DOWNLOAD_TOKEN_TTL_SECONDS: "300";
		DOWNLOAD_TOKEN_KEY_VERSION: "prod";
		RATE_LIMIT_WINDOW_SECONDS: "60";
		RATE_LIMIT_MAX_REQUESTS: "60";
		ENABLE_DIRECT_ADMIN_API: "false";
		RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "APP_ID" | "GITHUB_OWNER" | "GITHUB_REPO" | "MANIFEST_CACHE_TTL_SECONDS" | "DOWNLOAD_TOKEN_TTL_SECONDS" | "DOWNLOAD_TOKEN_KEY_VERSION" | "RATE_LIMIT_WINDOW_SECONDS" | "RATE_LIMIT_MAX_REQUESTS" | "ENABLE_DIRECT_ADMIN_API">> {}
}
